site_name: Junior's way
site_description: A blog about programming and life
site_url: https://daxartio.github.io/blog/
docs_dir: content
locale: en

copyright: Copyright &copy; 2023 Danil Akhtarov

nav:
  - Home: index.md

theme:
  name: material
  language: en
  features:
    - navigation.expand
  palette:
    primary: black
    accent: yellow

plugins:
  - search:
      lang: en
  - tags
  - blog:
      blog_dir: .
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      abstract_chars_count: -1

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
