site_name: Software Architect
site_description: A blog about programming and life
site_url: https://daxartio.github.io/blog/
docs_dir: content

copyright: Copyright &copy; 2024 Danil Akhtarov
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daxartio
    - icon: material/card-account-details
      link: https://daxartio.github.io

nav:
  - Home: index.md

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.instant
    - navigation.expand
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: yellow
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: yellow
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: en
  - tags
  - social
  - blog:
      blog_dir: .
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      abstract_chars_count: -1

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
